compile:
  image: nvidia/cuda:10.0-devel-ubuntu18.04
  script:
  - apt-get update -q -y && apt-get install -y -q zlib1g-dev wget
  - wget https://cmake.org/files/v3.13/cmake-3.13.2-Linux-x86_64.sh -O /cmake-3.13.2-Linux-x86_64.sh
  - mkdir /opt/cmake
  - sh /cmake-3.13.2-Linux-x86_64.sh --prefix=/opt/cmake --skip-license
  - ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
  - ln -s /opt/cmake/bin/ctest /usr/local/bin/ctest
  - mkdir build
  - cd build
  - cmake ..
  - make

performance:
  image: docker:git
  script:
  - mkdir results
  - echo "lol" > result/performance.json
  artifacts:
    paths:
      - results
    reports:
      performance: performance.json
      
