###############################################################################
# (c) Copyright 2018-2020 CERN for the benefit of the LHCb Collaboration      #
###############################################################################

# used in definitions for all possible target devices.
.run_matrix_jobs_minimal:
  parallel:
    matrix:
      # run_throughput tests
      - TEST_NAME: "run_throughput"
        SEQUENCE: ["hlt1_pp_default"]
        DATA_TAG: ["upgrade_mc_minbias_scifi_v5_000"]
        #DATA_TAG: ["MiniBrunel_2018_MinBias_FTv4_DIGI_1k"]
 
      # efficiency tests
      - TEST_NAME: "run_physics_efficiency"
        SEQUENCE: ["hlt1_pp_validation"]
        DATA_TAG: ["Upgrade_BsPhiPhi_MD_FTv4_DIGI_1k"]


.run_matrix_jobs_full:
  parallel:
    matrix:
      # run throughput, no_gec
      # - TEST_NAME: "run_throughput"
      #   BUILD_TYPE: ["RelWithDebInfo"]
      #   SEQUENCE: ["hlt1_pp_no_gec"]
      #   DATA_TAG: ["upgrade_mc_minbias_scifi_v5_000"]
      #   #DATA_TAG: ["MiniBrunel_2018_MinBias_FTv4_DIGI_1k"]

      # # run throughput, default, SMOG2_pppHe
      # - TEST_NAME: "run_throughput"
      #   BUILD_TYPE: ["RelWithDebInfo"]
      #   SEQUENCE: ["hlt1_pp_default"]
      #   DATA_TAG: ["SMOG2_pppHe_1k"]

      # run throughput, scifi_v6
      - TEST_NAME: "run_throughput"
        BUILD_TYPE: ["RelWithDebInfo"]
        SEQUENCE: ["hlt1_pp_scifi_v6"]
        DATA_TAG: ["SciFiv6_upgrade_DC19_01_MinBiasMD_1k"]
        GEOMETRY: ["scifi_v6"]

      # run physics efficiency, scifi_v6
      - TEST_NAME: "run_physics_efficiency"
        BUILD_TYPE: ["RelWithDebInfo"]
        SEQUENCE: ["hlt1_pp_scifi_v6_validation"]
        DATA_TAG: ["SciFiv6_upgrade_DC19_01_Bs2PhiPhiMD_1k"]
        GEOMETRY: ["scifi_v6"]

      # FIXME
      # - TEST_NAME: "run_physics_efficiency"
      #   BUILD_TYPE: ["Debug"]
      #   OPTIONS: ["USE_ROOT"]
      #   SEQUENCE: ["hlt1_pp_validation"]
      #   DATA_TAG: ["Upgrade_BsPhiPhi_MD_FTv4_DIGI_1k"]

      - TEST_NAME: "run_built_tests"
        BUILD_TYPE: Debug #[RelWithDebInfo, Debug]
        OPTIONS: [BUILD_TESTS+ENABLE_CONTRACTS]
        SEQUENCE: ["hlt1_pp_default"]

      # run physics efficiency, complex_validation
      # - TEST_NAME: "run_physics_efficiency"
      #   BUILD_TYPE: ["RelWithDebInfo"]
      #   SEQUENCE: ["hlt1_complex_validation"]
      #   DATA_TAG: ["Upgrade_BsPhiPhi_MD_FTv4_DIGI_1k"]

      # - TEST_NAME: "run_throughput"
      #   SEQUENCE: ["hlt1_pp_scifi_v6"]
      #   DATA_TAG: ["upgrade-magdown-sim10-up08-30000000-digi_01"]
      #   GEOMETRY: ["sim10_up08_md"]
  

.run_jobs:
  extends:
    - .base_job
    - .default_rules

  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    LCG_ARCHITECTURE: "x86_64-centos7-clang10-opt"
    BUILD_TYPE: "RelWithDebInfo"

  retry: 2

  artifacts:
    expire_in: 1 day
    paths:
      - output_*
      - run_*_output_*
      - validation_output*/*
      - ./*-unit-tests.xml
    reports:
      junit:
        - ./*-unit-tests.xml
      metrics: ./**/metrics.txt

.run_jobs_minimal:
  extends:
    - .run_jobs
    - .run_matrix_jobs_minimal

.run_jobs_full:
  extends:
    - .run_jobs
    - .run_matrix_jobs_full
    - .default_rules_always_run
  stage: "run full"


.run_toggle_run_changes:
  extends:
    - .run_jobs
  stage: run
  parallel:
    matrix:
      - TEST_NAME: "run_toggle_run_changes"
        SEQUENCE: ["hlt1_pp_validation"]
        DATA_TAG: "MiniBrunel_2018_MinBias_FTv4_DIGI_1k"
        RUN_CHANGES: ["ON", "OFF"]
  artifacts:
    expire_in: 1 day
    paths:
      - run_*_run_changes_output_*/*
