###############################################################################
# (c) Copyright 2018-2020 CERN for the benefit of the LHCb Collaboration      #
###############################################################################


# used in definitions for all possible target devices.
.run_matrix_jobs_minimal:
  parallel:
    matrix:
      # run_throughput tests
      - TEST_NAME: "run_throughput"
        SEQUENCE: ["hlt1_pp_default"]
        DATA_TAG: ["upgrade_mc_minbias_scifi_v5_retinacluster_000"]
        #DATA_TAG: ["MiniBrunel_2018_MinBias_FTv4_DIGI_retinacluster"]

      # efficiency tests
      - TEST_NAME: "run_physics_efficiency"
        SEQUENCE: ["hlt1_pp_validation"]
        DATA_TAG: ["Upgrade_BsPhiPhi_MD_FTv4_DIGI_retinacluster"]


.run_matrix_jobs_full:
  parallel:
    matrix:

      # run throughput, contracts enabled
      - TEST_NAME: "run_throughput"
        SEQUENCE: ["hlt1_pp_default"]
        DATA_TAG: ["upgrade_mc_minbias_scifi_v5_retinacluster_000"]
        OPTIONS: [BUILD_TESTING+ENABLE_CONTRACTS]


      # run throughput, no_gec
      - TEST_NAME: "run_throughput"
        BUILD_TYPE: ["RelWithDebInfo"]
        SEQUENCE: ["hlt1_pp_no_gec"]
        DATA_TAG: ["upgrade_mc_minbias_scifi_v5_retinacluster_000"]
        #DATA_TAG: ["MiniBrunel_2018_MinBias_FTv4_DIGI_retinacluster"]

      # run throughput, default, SMOG2_pppHe
      - TEST_NAME: "run_throughput"
        BUILD_TYPE: ["RelWithDebInfo"]
        SEQUENCE: ["hlt1_pp_default"]
        DATA_TAG: ["SMOG2_pppHe_retinacluster"]
        GEOMETRY: ["smog"]

      # Allen clustering jobs
      - TEST_NAME: "run_throughput"
        BUILD_TYPE: ["RelWithDebInfo"]
        SEQUENCE: ["hlt1_pp_veloSP"]
        DATA_TAG: ["upgrade_mc_minbias_scifi_v5_000"]

      - TEST_NAME: "run_physics_efficiency"
        BUILD_TYPE: ["RelWithDebInfo"]
        SEQUENCE: ["hlt1_pp_veloSP_validation"]
        DATA_TAG: ["SciFiv6_upgrade_DC19_01_Bs2PhiPhiMD_retinacluster"]
        GEOMETRY: ["scifi_v6"]

      # run throughput, scifi_v6
      - TEST_NAME: "run_throughput"
        BUILD_TYPE: ["RelWithDebInfo"]
        SEQUENCE: ["hlt1_pp_default"]
        DATA_TAG: ["SciFiv6_upgrade_DC19_01_MinBiasMD_retinacluster"]
        GEOMETRY: ["scifi_v6"]

      # run physics efficiency, scifi_v6
      - TEST_NAME: "run_physics_efficiency"
        BUILD_TYPE: ["RelWithDebInfo"]
        SEQUENCE: ["hlt1_pp_validation"]
        DATA_TAG: ["SciFiv6_upgrade_DC19_01_Bs2PhiPhiMD_retinacluster"]
        GEOMETRY: ["scifi_v6"]

      # efficiency tests, SMOG2 pHe
      - TEST_NAME: "run_physics_efficiency"
        SEQUENCE: ["hlt1_pp_validation"]
        DATA_TAG: ["SMOG2_pHe_5k_retinacluster"]
        GEOMETRY: ["smog"]

      # FIXME
      # - TEST_NAME: "run_physics_efficiency"
      #   BUILD_TYPE: ["Debug"]
      #   OPTIONS: ["USE_ROOT"]
      #   SEQUENCE: ["hlt1_pp_validation"]
      #   DATA_TAG: ["Upgrade_BsPhiPhi_MD_FTv4_DIGI_retinacluster"]

      - TEST_NAME: "run_built_tests"
        BUILD_TYPE: [RelWithDebInfo, Debug]
        OPTIONS: [BUILD_TESTING+ENABLE_CONTRACTS]
        SEQUENCE: ["hlt1_pp_default"]

      # run physics efficiency, complex_validation
      - TEST_NAME: "run_physics_efficiency"
        BUILD_TYPE: ["RelWithDebInfo"]
        SEQUENCE: ["hlt1_complex_validation"]
        DATA_TAG: ["Upgrade_BsPhiPhi_MD_FTv4_DIGI_retinacluster"]

      - TEST_NAME: "run_throughput"
        SEQUENCE: ["hlt1_pp_default"]
        DATA_TAG: ["upgrade-magdown-sim10-up08-30000000-digi_01_retinacluster"]
        GEOMETRY: ["sim10_up08_md"]


.run_jobs:
  extends:
    - .base_job
    - .default_rules

  tags: ['$DEVICE_ID']

  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    LCG_ARCHITECTURE: "x86_64-centos7-clang12-opt"
    BUILD_TYPE: "RelWithDebInfo"

  retry: 2

  artifacts:
    expire_in: 1 day
    paths:
      - output_*
      - run_*_output_*
      - validation_output*/*
      - ./*-unit-tests.xml
    reports:
      junit:
        - ./*-unit-tests.xml
      metrics: ./**/metrics.txt

.run_jobs_minimal:
  extends:
    - .run_jobs
    - .run_matrix_jobs_minimal
  stage: "run"

.run_jobs_full:
  extends:
    - .run_jobs
    - .run_matrix_jobs_full
    - .default_rules_always_run
  stage: "run full"


.run_toggle_run_changes:
  extends:
    - .run_jobs
  stage: run
  parallel:
    matrix:
      - TEST_NAME: "run_toggle_run_changes"
        SEQUENCE: ["hlt1_pp_validation"]
        DATA_TAG: "MiniBrunel_2018_MinBias_FTv4_DIGI_retinacluster"
        RUN_CHANGES: ["ON", "OFF"]
  artifacts:
    expire_in: 1 day
    paths:
      - run_*_run_changes_output_*/*
