###############################################################################
# (c) Copyright 2018-2020 CERN for the benefit of the LHCb Collaboration      #
###############################################################################


# used in definitions for all possible target devices.
.run_matrix_jobs_minimal:
  parallel:
    matrix:
      # run_throughput tests for default sequence
      - TEST_NAME: "run_efficiency_throughput"
        RUN_EFFICIENCY_SEQUENCE: ["hlt1_pp_validation"]
        RUN_EFFICIENCY_DATA_TAG: ["Upgrade_BsPhiPhi_MD_FTv4_DIGI_retinacluster_v1"]

        RUN_THROUGHPUT_SEQUENCE: ["hlt1_pp_default"]
        RUN_THROUGHPUT_DATA_TAG: ["upgrade_mc_minbias_scifi_v5_retinacluster_000_v1"]

.run_matrix_jobs_full: 
  variables:
    TEST_NAME: "run_efficiency_throughput"

  parallel:
    matrix:
      
      # Contracts
      - RUN_EFFICIENCY: "NO_EFFICIENCY"

        RUN_THROUGHPUT_SEQUENCE: 
          - "hlt1_pp_default"
          - "hlt1_pp_matching"
        RUN_THROUGHPUT_DATA_TAG: ["upgrade_mc_minbias_scifi_v5_retinacluster_000_v1"]

        OPTIONS: BUILD_TESTING+ENABLE_CONTRACTS
        TPUT_REPORT: "NO_REPORT"


      # SMOG (Default)
      - RUN_EFFICIENCY_SEQUENCE: hlt1_pp_validation
        RUN_EFFICIENCY_DATA_TAG: SMOG2_pHe_5k_retinacluster_v1
        RUN_EFFICIENCY_GEOMETRY: SMOG2_pppHe

        RUN_THROUGHPUT_SEQUENCE: hlt1_pp_default
        RUN_THROUGHPUT_DATA_TAG: SMOG2_pppHe_retinacluster_v1
        RUN_THROUGHPUT_GEOMETRY: SMOG2_pppHe

      # SMOG2
      - RUN_EFFICIENCY_SEQUENCE: hlt1_pp_SMOG2_validation
        RUN_EFFICIENCY_DATA_TAG: SMOG2_pHe_5k_retinacluster_v1
        RUN_EFFICIENCY_GEOMETRY: SMOG2_pppHe

        RUN_THROUGHPUT_SEQUENCE: hlt1_pp_SMOG2_default
        RUN_THROUGHPUT_DATA_TAG: SMOG2_pppHe_retinacluster_v1
        RUN_THROUGHPUT_GEOMETRY: SMOG2_pppHe

      # SMOG (Matching sequence)
      - RUN_EFFICIENCY_SEQUENCE: hlt1_pp_matching_validation
        RUN_EFFICIENCY_DATA_TAG: SMOG2_pHe_5k_retinacluster_v1
        RUN_EFFICIENCY_GEOMETRY: SMOG2_pppHe

        RUN_THROUGHPUT_SEQUENCE: hlt1_pp_matching
        RUN_THROUGHPUT_DATA_TAG: SMOG2_pppHe_retinacluster_v1
        RUN_THROUGHPUT_GEOMETRY: SMOG2_pppHe

      # No GEC (no eff)

      # No UT, No GEC (no eff)

      # Matching (no eff)

      # 
      # - TEST_NAME: "run_physics_efficiency"
        # SEQUENCE: 
        #   - hlt1_pp_validation
        #   - hlt1_pp_no_ut_validation
        #   - hlt1_pp_matching_validation
        # DATA_TAG: ["SciFiv6_upgrade_DC19_01_Bs2PhiPhiMD_retinacluster_v1"]
        # GEOMETRY: ["upgrade_DC19_01_MinBiasMD"]




# run_throughput jobs go in this matrix.
.run_matrix_jobs_full_throughput:
  variables:
    TEST_NAME: "run_throughput"
  parallel:
    matrix:
      # run throughput, contracts enabled
      - SEQUENCE: ["hlt1_pp_default", "hlt1_pp_matching"]
        DATA_TAG: ["upgrade_mc_minbias_scifi_v5_retinacluster_000_v1"]
        OPTIONS: [BUILD_TESTING+ENABLE_CONTRACTS]
        TPUT_REPORT: "NO_REPORT" # don't publish throughput report

      # run throughput, no_gec
      - SEQUENCE: 
          - hlt1_pp_no_gec
          - hlt1_pp_no_gec_no_ut
          - hlt1_pp_SMOG2_default
        DATA_TAG: ["upgrade_mc_minbias_scifi_v5_retinacluster_000_v1"]
        #DATA_TAG: ["MiniBrunel_2018_MinBias_FTv4_DIGI_retinacluster_v1"]

      # # run throughput, default, SMOG2_pppHe
      # - SEQUENCE: 
      #     - hlt1_pp_default
      #     - hlt1_pp_matching
      #     - hlt1_pp_SMOG2_default
      #   DATA_TAG: ["SMOG2_pppHe_retinacluster_v1"]
      #   GEOMETRY: ["SMOG2_pppHe"]

      # run throughput, PbPb, MB PbPb
      - TEST_NAME: "run_throughput"
        SEQUENCE: ["hlt1_PbPb_default"]
        DATA_TAG: ["MB_PbPb_01"]

      # Allen clustering jobs
      - SEQUENCE: ["hlt1_pp_veloSP"]
        DATA_TAG: ["upgrade_mc_minbias_scifi_v5_000"]

      # run throughput, scifi_v6
      - SEQUENCE: ["hlt1_pp_default", "hlt1_pp_matching"]
        DATA_TAG: ["SciFiv6_upgrade_DC19_01_MinBiasMD_retinacluster_v1"]
        GEOMETRY: ["upgrade_DC19_01_MinBiasMD"]

      # run throughput, calov4
      - SEQUENCE: ["calo"]
        DATA_TAG: ["sim-20190912-vc-md100-FTv7-calov4"]
        GEOMETRY: ["MiniBrunel_2018_MinBias_FTv4_DIGI_ecalv4"]
        TPUT_REPORT: "NO_REPORT" # don't publish throughput report

      # run throughput, scifiv7
      - SEQUENCE: ["scifi_decoding"]
        DATA_TAG: ["SciFiV7_not_compressed"]
        GEOMETRY: ["MiniBrunel_2018_MinBias_FTv4_DIGI_ecalv4_scifiv7"]
        TPUT_REPORT: "NO_REPORT" # don't publish throughput report

      # run throughput, muonv3
      - SEQUENCE: ["muon_decoding"]
        DATA_TAG: ["Run_0000232759_20220605-105749-418_MCEB02"]
        GEOMETRY: ["MiniBrunel_2018_MinBias_FTv4_DIGI_ecalv4_scifiv7_muonv3"]
        TPUT_REPORT: "NO_REPORT" # don't publish throughput report

      - SEQUENCE: 
         - hlt1_pp_default
         - hlt1_pp_matching
        DATA_TAG: ["upgrade-magdown-sim10-up08-30000000-digi_01_retinacluster_v1"]
        GEOMETRY: ["upgrade-magdown-sim10-up08-11102202-digi"]

      # run throughput, forward no ut, matching
      - SEQUENCE: 
          - hlt1_pp_matching
          - hlt1_pp_no_ut
        DATA_TAG: ["upgrade_mc_minbias_scifi_v5_retinacluster_000_v1"]


# efficiency and other tests go here
.run_matrix_jobs_full_efficiency:
  parallel:
    matrix:
      # run physics efficiency, pp_SMOG2_default, minbias_scifi_v5
      - TEST_NAME: "run_physics_efficiency"
        BUILD_TYPE: ["RelWithDebInfo"]
        SEQUENCE: ["hlt1_pp_SMOG2_validation"]
        DATA_TAG: ["upgrade_mc_minbias_scifi_v5_retinacluster_000_v1"]

      - TEST_NAME: "run_built_tests"
        LCG_OPTIMIZATION: [opt, dbg]
        OPTIONS: [BUILD_TESTING+ENABLE_CONTRACTS]
        SEQUENCE: ["hlt1_pp_default"]

      # run physics efficiency, scifi_v6
      # forward no ut, scifi v6
      - TEST_NAME: "run_physics_efficiency"
        SEQUENCE: 
          - hlt1_pp_validation
          - hlt1_pp_no_ut_validation
          - hlt1_pp_matching_validation
        DATA_TAG: ["SciFiv6_upgrade_DC19_01_Bs2PhiPhiMD_retinacluster_v1"]
        GEOMETRY: ["upgrade_DC19_01_MinBiasMD"]

      # # efficiency tests, SMOG2 pHe
      # - TEST_NAME: "run_physics_efficiency"
      #   SEQUENCE: 
      #     - hlt1_pp_validation
      #     - hlt1_pp_SMOG2_validation
      #     - hlt1_pp_matching_validation
      #   DATA_TAG: ["SMOG2_pHe_5k_retinacluster_v1"]
      #   GEOMETRY: ["SMOG2_pppHe"]

      - TEST_NAME: "run_physics_efficiency"
        SEQUENCE: ["hlt1_pp_veloSP_validation"]
        DATA_TAG: ["SciFiv6_upgrade_DC19_01_Bs2PhiPhiMD_1k"]
        GEOMETRY: ["upgrade_DC19_01_MinBiasMD"]



## End of test matrices


.run_jobs:
  extends:
    # - .base_job
    - .default_rules
  stage: "run full"
  tags: ['$DEVICE_ID']

  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    LCG_SYSTEM: "x86_64_v3-centos7-clang12"
    LCG_OPTIMIZATION: "opt"
    TEST_GROUP: "full"

  script:
    - python -m venv .venv && source .venv/bin/activate && pip install colorlog pyyaml tabulate
    - python scripts/ci/run_tests.py --allen-wrapper scripts/ci/allen_wrapper.sh --test-config scripts/ci/test_config.yaml --test-group ${TEST_GROUP}

  retry: 1

  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - AllenCI_full.log
      - output_*
      - run_*_output_*
      - validation_output*/*
      - ./*-unit-tests.xml
    reports:
      junit:
        - ./*-unit-tests.xml
      metrics: ./**/metrics.txt

.run_jobs_minimal:
  extends:
    - .run_jobs
    # - .run_matrix_jobs_minimal
  variables:
    TEST_GROUP: "minimal"
  stage: "run"

.run_toggle_run_changes:
  extends:
    - .run_jobs
  stage: run
  parallel:
    matrix:
      - TEST_NAME: "run_toggle_run_changes"
        SEQUENCE: ["hlt1_pp_validation", "hlt1_pp_matching_validation"]
        DATA_TAG: "MiniBrunel_2018_MinBias_FTv4_DIGI_retinacluster_v1"
  artifacts:
    expire_in: 1 day
    paths:
      - run_*_run_changes_output_*/*
