###############################################################################
# (c) Copyright 2018-2020 CERN for the benefit of the LHCb Collaboration      #
###############################################################################


.geforcertx3090:
  variables:
    DEVICE_ID: "geforcertx3090"


.geforcertx2080ti:
  variables:
    DEVICE_ID: "geforcertx2080ti"


.a6000:
  variables:
    DEVICE_ID: "a6000"


.a5000:
  variables:
    DEVICE_ID: "a5000"


.mi100:
  variables:
    DEVICE_ID: "mi100"

.epyc7502:
  variables:
    DEVICE_ID: "epyc7502"

